// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlittdjhmdglyfnddfhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1saXR0ZGpobWRnbHlmbmRkZmhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTU3OTEsImV4cCI6MjA2NTc3MTc5MX0.9_oUBDnJD3MnaudNsepp9YF2EAT9a6nawH3n9q3qenI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);